### ISSUE TITLE
Hi Tobias,

### ISSUE THREAD

**Issue by OlafM2015** [TobiasVanDyk/Pico-MCU-from-Raspberry-Pi#1]
Great that you made this together. We have developed a Music player for people with Dementia based on Rpi's. However, the Rpi 's are difficult toe get. So we want to use the Pico in combinatie with the VS1053. ( wi use the adafruit music maker). 
Will build test in next weeks.
Any recommendations?
Thanks
Olaf
Ps we are a foundation and have an open source approach.

**Comment by TobiasVanDyk** [comment]
Hi Olaf - yes also the Pico is a fraction of the price of a Pi
I will add the complete Music Player code during the next few weeks - you can also look at this mod for a combined recorder-player on the Teensy Forum https://forum.pjrc.com/threads/70785-Teensy-LC-VS1053-musicPlayer-begin()-don-t-work-when-in-the-Main-loop
I will also look at porting that to the Pico later..

**Comment by TobiasVanDyk** [comment]
The Music Maker is here: https://www.adafruit.com/product/1790
It seems the only change needed is this here: https://learn.adafruit.com/adafruit-music-maker-shield-vs1053-mp3-wav-wave-ogg-vorbis-player?view=all

Adafruit_VS1053_FilePlayer musicPlayer = 
  // create breakout-example object!
  //Adafruit_VS1053_FilePlayer(BREAKOUT_RESET, BREAKOUT_CS, BREAKOUT_DCS, DREQ, CARDCS);
  // create shield-example object!
  Adafruit_VS1053_FilePlayer(SHIELD_RESET, SHIELD_CS, SHIELD_DCS, DREQ, CARDCS);

and adding SHIELD instead of BREAKOUT to the #defines

**Comment by TobiasVanDyk** [comment]
As a quick guide while I still remember the order in which I installed things on Windows 10x64 21H2 are:
1. Arduino Arduino IDE 1.8.19
2. Teensyduino 1.56 (you can leave this out - but is does install other versions of things such as the VS1053 lib)
3. The earlephilhower Aduino Pico port see the 2nd last pic on the main page for details
4. Newest Adafruit GFX, SSD1306, and VS1053 libraries

![ArduinoFolders](https://user-images.githubusercontent.com/22213123/182817951-e4f537da-3385-4944-ad88-14abf745283b.jpg)

**Comment by OlafM2015** [comment]
Hi, Build and tested first set-up Pico + VS1053 Music maker. Works excellent. Had some trouble with the SD card formatting and used the standard Simple Player (adafruit lib) to analyse (via serial monitor). 
Next step is making the connection with the Interface board, see picture. Great that you made the combination of  earlephilhower Aduino Pico port and the standard libs. Keep you updated in next week
![IMG_0756](https://user-images.githubusercontent.com/11895505/183712004-742a3b5e-0863-4dfe-8fac-fa3407d3aae6.JPG)

**Comment by TobiasVanDyk** [comment]
Looks great! I am now first setting up a display for touch control via an LCD with a Pico - then I will go back to the music player.
If you are allowed put some of your code up on your github once you are satisfied with it.
